Keras generators
Oslandia/mapillary_classification pull request #40
Opened 2018-04-05 08:27 UTC by delhomer

Integrate a new feature to Keras-based code: ability to build some data generators, either with Mapillary data or with random shapes. In latter case, some minor changes have been necessary, as the addition of a dummy class for representing background pixels.

A pair of tests has been introduced as well to consider the generator output shapes.

2018-04-05 10:21 UTC, garaud requested changes
Some comments. Maybe I would add some comments about `find_classes`.

2018-04-05 10:21 UTC, garaud commented on tests/test_generators.py
> +    assert(im_shape[0] == BATCH_SIZE)
You don't have to write parenthesis after the `assert`. Maybe you should write

`assert im_shapes[0] == BATCH_SIZE`

don't forget to write whitespaces before and after the `==`

Another comment: you can compare the shape instead of compare each element if you want, e.g.

`assert im_shape == (BATCH_SIZe, IMAGE_SIZE, IMAGE_SIZE, 3)`

2018-04-05 10:21 UTC, garaud commented on tests/test_generators.py
> +    config = utils.read_config("./data/mapillary/input/config_aggregate.json")
I think we should put a JSON file in the `tests` folder dedicated to the unit tests.

2018-04-05 10:21 UTC, garaud commented on tests/test_generators.py
> +import numpy as np
Are these imports necessary?

2018-04-05 10:21 UTC, garaud commented on tests/test_generators.py
> +"""Unit test associated to the generator building and feeding
I prefer "related" than "associated".

Keep the name of the test file consistent with the name of the related module. I think you can remove the `s` at the end of the `test_generators.py` filename

2018-04-05 10:21 UTC, garaud commented on deeposlandia/generator.py
> +        seed=SEED)
make the seed a parameter of the function, with a default value.

2018-04-05 10:21 UTC, garaud commented on deeposlandia/generator.py
> +def find_classes(img, config):
You also should test this function.

2018-04-05 10:21 UTC, garaud commented on deeposlandia/generator.py
> +    for class_id in range(nb_classes):
It's not really the id of each class? I suggest `idx` or `class_idx`

2018-04-05 10:21 UTC, garaud commented on deeposlandia/generator.py
> +    return mask
For my point of a view, a "mask" array is an array with booleans. You can use it with something like `a[mask]`.

2018-04-05 10:21 UTC, garaud commented on deeposlandia/generator.py
> +        Output matrix
Output matrix -> array with the index of each class for each pixel shape (batch, size, size, num_classes)

2018-04-05 10:21 UTC, garaud commented on deeposlandia/generator.py
> +        mask_generator = generator.flow_from_directory(
Maybe I would have been changed the name of these variable from my previous copy/pasting for this snippet. `labels_generator` is clearer than `masks_generator`.

2018-04-05 10:21 UTC, garaud commented on deeposlandia/generator.py
> +    zip
`zip` it's not a type. This is a function name which returns a generator. Maybe "generator" or "iterable". We can be more specific with a short sentence such as "iterate over the input image batch and label bach"...

2018-04-05 10:21 UTC, garaud commented on deeposlandia/generator.py
> +            mask[i][[[img[i, x, y, ::-1].tolist() == colors[class_id] for y in range(img.shape[2])]
I don't get the `::-1`. You have to inverse the order of some elements?

```python
a = np.arange(24).reshape((4, 6))
a[1, ::-1]
# array([11, 10,  9,  8,  7,  6])
a[1, :]
# array([ 6,  7,  8,  9, 10, 11])
```

2018-04-05 10:39 UTC, delhomer commented on tests/test_generators.py
> +    assert(im_shape[0] == BATCH_SIZE)
Ok, modified.

2018-04-05 10:42 UTC, delhomer commented on tests/test_generators.py
> +import numpy as np
There are not, I remove them in both test modules.

2018-04-05 10:42 UTC, delhomer commented on tests/test_generators.py
> +"""Unit test associated to the generator building and feeding
Done.

2018-04-05 10:48 UTC, delhomer commented on deeposlandia/generator.py
> +            mask[i][[[img[i, x, y, ::-1].tolist() == colors[class_id] for y in range(img.shape[2])]
Yes... It depends on the way we read the image. They are stored with OpenCV in a (B,G,R) format. However most draft tests have consisted in reading images with Pillow, which is simpler. And Pillow considers the (R, G, B) format...

However, I am not able to say which format is chosen by Keras `flow_frow_directory` method. This point needs to be vigilant regarding the input data we get.

2018-04-05 12:13 UTC, delhomer commented on deeposlandia/generator.py
> +        seed=SEED)
Done.

2018-04-05 12:15 UTC, delhomer commented on deeposlandia/generator.py
> +    return mask
Ok, got it, I change the variable name.

2018-04-05 12:20 UTC, delhomer commented on deeposlandia/generator.py
> +        Output matrix
Ok for the description updating.

2018-04-05 12:21 UTC, delhomer commented on deeposlandia/generator.py
> +        mask_generator = generator.flow_from_directory(
The name is now `label_generator`.

2018-04-05 12:22 UTC, delhomer commented on deeposlandia/generator.py
> +            mask[i][[[img[i, x, y, ::-1].tolist() == colors[class_id] for y in range(img.shape[2])]
I've added a comment about this point in the docstring.

2018-04-05 12:23 UTC, delhomer commented on deeposlandia/generator.py
> +    zip
The docstring has been modified.

2018-04-05 12:31 UTC, delhomer commented on deeposlandia/generator.py
> +    for class_id in range(nb_classes):
I am not sure to really understand this point. I have standardized the way of iterating over the label ids (just did as in `to_categorical` method : `for idx, class_id in enumerate(label_ids):`). However the fact that the good labels are put in the good array indices is not clear to me.

2018-04-05 12:35 UTC, delhomer commented on tests/test_generators.py
> +    config = utils.read_config("./data/mapillary/input/config_aggregate.json")
We should put some image files as well, don't we ?

2018-04-05 12:46 UTC, garaud commented
Yes, you're right.
Raphael Delhome writes:

> delhomer commented on this pull request.
>
>
>
>> +
> +import numpy as np
> +import keras as K
> +
> +from deeposlandia import generator, network, utils
> +
> +def test_mapillary_generator():
> +    """Test the data generator for the Mapillary dataset
> +
> +    """
> +    dataset = "mapillary"
> +    IMAGE_SIZE = 256
> +    BATCH_SIZE = 10
> +    datapath = ("data/mapillary/preprocessed/" + str(IMAGE_SIZE)
> +                + "_aggregated/training/")
> +    config = utils.read_config("./data/mapillary/input/config_aggregate.json")
>
> We should put some image files as well, don't we ?


-- 
Damien Garaud
Data Scientist – Developer, Oslandia
http://oslandia.com

2018-04-05 15:39 UTC, delhomer commented
Some modifications have been implemented since your last comments:
- Labels of Shapes dataset are now stored as one-channelled images, with values corresponding to their class ids.
- Consequently we do not need the `find_classes` method any more, it has been dropped.
- The distinction between both dataset is done in `create_generator` method, this distinction is only done on `label_ids` recovering.
- Consequently changes to `to_categorical` method have been cancelled, the method is just as you provided it in `segnet_keras.py`.
- A test dedicated to the `to_categorical` method has been introduced.
- Some data has been added into the `tests/data` repository, in order to make the tests replicable.

2018-04-06 06:35 UTC, garaud approved these changes

2018-04-06 06:36 UTC, garaud commented
Looks good for me.

2018-04-06 07:08 UTC, merged