Model inference
Oslandia/mapillary_classification pull request #62
Opened 2018-04-27 16:45 UTC by delhomer

This PR introduces a new module that will make the inference easier in further developments (for instance, in a web app).

Until now, inference was done only after training a model. It was possible to do inference only, by passing 0 to `nb_epochs`, or alternatively a number smaller than the checkpoint training step, if a backup exists. This was quite unpractical, as the program arguments are training-focused.

Here we can predict labels on a given image by simply entering the following command (as an example):
```
python deeposlandia/inference.py -D dataset -i path_to_image/image_name.png
```

Additionally, the `prepare_folders` function has been splitted into three more precise functions:
- `prepare_input_folder`, which is called during dataset generation (*cf* `deeposlandia/datagen.py`).
- `prepare_prepro_folder` which is called during dataset generation and training process: such directories are filled during the former and the images that they contain are scanned during the latter.
- `prepare_output_folder` which is called when results are produced, either during training process (model backup creations) or during inference (model backup recovering).

2018-04-30 08:23 UTC, garaud requested changes

2018-04-30 08:23 UTC, garaud commented on deeposlandia/inference.py
> +    image_paths = [item for sublist in [glob.glob(f) for f in args.image_paths]
You can turn these comprehension lists into generator expressions. Such as:

```python
(item for sublist in (glob.glob(f) for f in args.image_paths) for item in sublist)
```

Moreover, it's not clear for me, at least when I read the first time, that you want to flatten the list of image files. Can I propose something like:

```python
images_paths = (glob.glob(f) for f in args.image_paths)
# flatten the result of [[image1, image2], [image10, image11]]
image_paths = itertools.chain(*image_paths)
```

with the great package [itertools](https://docs.python.org/3/library/itertools.html)

2018-04-30 08:23 UTC, garaud commented on deeposlandia/inference.py
> +    print( prepro_folder['training_config'] )
remove the print. Or replace it by a logging message.

2018-05-02 08:20 UTC, delhomer commented on deeposlandia/inference.py
> +    print( prepro_folder['training_config'] )
Useless 'print' statement, it has been removed.

2018-05-02 09:38 UTC, delhomer commented on deeposlandia/inference.py
> +    image_paths = [item for sublist in [glob.glob(f) for f in args.image_paths]
I agree, `itertools` is really convenient. However I'm not sure to want a iterator there.

The iterator is consumed in the first loop, when the `x_test` variable is built. But its items are not available any more in the last loop, when results are printed: how do we get the image filenames if such a structure is chosen?

2018-05-02 12:58 UTC, garaud approved these changes

2018-05-02 13:36 UTC, merged